#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunriseLibrary.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ql_thu_vien_sunrise")]
	public partial class SunriseDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertvai_tro(vai_tro instance);
    partial void Updatevai_tro(vai_tro instance);
    partial void Deletevai_tro(vai_tro instance);
    partial void Inserttai_lieu(tai_lieu instance);
    partial void Updatetai_lieu(tai_lieu instance);
    partial void Deletetai_lieu(tai_lieu instance);
    partial void Inserttai_khoan(tai_khoan instance);
    partial void Updatetai_khoan(tai_khoan instance);
    partial void Deletetai_khoan(tai_khoan instance);
    partial void Insertphieu_muon_tra(phieu_muon_tra instance);
    partial void Updatephieu_muon_tra(phieu_muon_tra instance);
    partial void Deletephieu_muon_tra(phieu_muon_tra instance);
    partial void Insertphan_loai_tai_lieu(phan_loai_tai_lieu instance);
    partial void Updatephan_loai_tai_lieu(phan_loai_tai_lieu instance);
    partial void Deletephan_loai_tai_lieu(phan_loai_tai_lieu instance);
    partial void Insertban_sao_tai_lieu(ban_sao_tai_lieu instance);
    partial void Updateban_sao_tai_lieu(ban_sao_tai_lieu instance);
    partial void Deleteban_sao_tai_lieu(ban_sao_tai_lieu instance);
    partial void Insertban_doc(ban_doc instance);
    partial void Updateban_doc(ban_doc instance);
    partial void Deleteban_doc(ban_doc instance);
    #endregion
		
		public SunriseDataDataContext() : 
				base(global::SunriseLibrary.Properties.Settings.Default.ql_thu_vien_sunriseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SunriseDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SunriseDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SunriseDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SunriseDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vai_tro> vai_tros
		{
			get
			{
				return this.GetTable<vai_tro>();
			}
		}
		
		public System.Data.Linq.Table<tai_lieu> tai_lieus
		{
			get
			{
				return this.GetTable<tai_lieu>();
			}
		}
		
		public System.Data.Linq.Table<tai_khoan> tai_khoans
		{
			get
			{
				return this.GetTable<tai_khoan>();
			}
		}
		
		public System.Data.Linq.Table<phieu_muon_tra> phieu_muon_tras
		{
			get
			{
				return this.GetTable<phieu_muon_tra>();
			}
		}
		
		public System.Data.Linq.Table<phan_loai_tai_lieu> phan_loai_tai_lieus
		{
			get
			{
				return this.GetTable<phan_loai_tai_lieu>();
			}
		}
		
		public System.Data.Linq.Table<ban_sao_tai_lieu> ban_sao_tai_lieus
		{
			get
			{
				return this.GetTable<ban_sao_tai_lieu>();
			}
		}
		
		public System.Data.Linq.Table<ban_doc> ban_docs
		{
			get
			{
				return this.GetTable<ban_doc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vai_tro")]
	public partial class vai_tro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_vai_tro;
		
		private string _ten_vai_tro;
		
		private string _mo_ta;
		
		private EntitySet<tai_khoan> _tai_khoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_vai_troChanging(int value);
    partial void Onma_vai_troChanged();
    partial void Onten_vai_troChanging(string value);
    partial void Onten_vai_troChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    #endregion
		
		public vai_tro()
		{
			this._tai_khoans = new EntitySet<tai_khoan>(new Action<tai_khoan>(this.attach_tai_khoans), new Action<tai_khoan>(this.detach_tai_khoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_vai_tro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_vai_tro
		{
			get
			{
				return this._ma_vai_tro;
			}
			set
			{
				if ((this._ma_vai_tro != value))
				{
					this.Onma_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ma_vai_tro = value;
					this.SendPropertyChanged("ma_vai_tro");
					this.Onma_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_vai_tro", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_vai_tro
		{
			get
			{
				return this._ten_vai_tro;
			}
			set
			{
				if ((this._ten_vai_tro != value))
				{
					this.Onten_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ten_vai_tro = value;
					this.SendPropertyChanged("ten_vai_tro");
					this.Onten_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(255)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vai_tro_tai_khoan", Storage="_tai_khoans", ThisKey="ma_vai_tro", OtherKey="ma_vai_tro")]
		public EntitySet<tai_khoan> tai_khoans
		{
			get
			{
				return this._tai_khoans;
			}
			set
			{
				this._tai_khoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tai_khoans(tai_khoan entity)
		{
			this.SendPropertyChanging();
			entity.vai_tro = this;
		}
		
		private void detach_tai_khoans(tai_khoan entity)
		{
			this.SendPropertyChanging();
			entity.vai_tro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tai_lieu")]
	public partial class tai_lieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_tai_lieu;
		
		private int _ma_phan_loai;
		
		private string _ma_doc;
		
		private string _ten_tai_lieu;
		
		private string _tac_gia;
		
		private string _nha_xuat_ban;
		
		private System.Nullable<int> _nam_xuat_ban;
		
		private string _loai_tai_lieu;
		
		private string _mo_ta;
		
		private string _duong_dan_file;
		
		private string _quyen_truy_cap;
		
		private System.Nullable<System.DateTime> _ngay_nhap;
		
		private EntitySet<ban_sao_tai_lieu> _ban_sao_tai_lieus;
		
		private EntityRef<phan_loai_tai_lieu> _phan_loai_tai_lieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_tai_lieuChanging(int value);
    partial void Onma_tai_lieuChanged();
    partial void Onma_phan_loaiChanging(int value);
    partial void Onma_phan_loaiChanged();
    partial void Onma_docChanging(string value);
    partial void Onma_docChanged();
    partial void Onten_tai_lieuChanging(string value);
    partial void Onten_tai_lieuChanged();
    partial void Ontac_giaChanging(string value);
    partial void Ontac_giaChanged();
    partial void Onnha_xuat_banChanging(string value);
    partial void Onnha_xuat_banChanged();
    partial void Onnam_xuat_banChanging(System.Nullable<int> value);
    partial void Onnam_xuat_banChanged();
    partial void Onloai_tai_lieuChanging(string value);
    partial void Onloai_tai_lieuChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onduong_dan_fileChanging(string value);
    partial void Onduong_dan_fileChanged();
    partial void Onquyen_truy_capChanging(string value);
    partial void Onquyen_truy_capChanged();
    partial void Onngay_nhapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_nhapChanged();
    #endregion
		
		public tai_lieu()
		{
			this._ban_sao_tai_lieus = new EntitySet<ban_sao_tai_lieu>(new Action<ban_sao_tai_lieu>(this.attach_ban_sao_tai_lieus), new Action<ban_sao_tai_lieu>(this.detach_ban_sao_tai_lieus));
			this._phan_loai_tai_lieu = default(EntityRef<phan_loai_tai_lieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tai_lieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_tai_lieu
		{
			get
			{
				return this._ma_tai_lieu;
			}
			set
			{
				if ((this._ma_tai_lieu != value))
				{
					this.Onma_tai_lieuChanging(value);
					this.SendPropertyChanging();
					this._ma_tai_lieu = value;
					this.SendPropertyChanged("ma_tai_lieu");
					this.Onma_tai_lieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_phan_loai", DbType="Int NOT NULL")]
		public int ma_phan_loai
		{
			get
			{
				return this._ma_phan_loai;
			}
			set
			{
				if ((this._ma_phan_loai != value))
				{
					if (this._phan_loai_tai_lieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_phan_loaiChanging(value);
					this.SendPropertyChanging();
					this._ma_phan_loai = value;
					this.SendPropertyChanged("ma_phan_loai");
					this.Onma_phan_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_doc", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ma_doc
		{
			get
			{
				return this._ma_doc;
			}
			set
			{
				if ((this._ma_doc != value))
				{
					this.Onma_docChanging(value);
					this.SendPropertyChanging();
					this._ma_doc = value;
					this.SendPropertyChanged("ma_doc");
					this.Onma_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_tai_lieu", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ten_tai_lieu
		{
			get
			{
				return this._ten_tai_lieu;
			}
			set
			{
				if ((this._ten_tai_lieu != value))
				{
					this.Onten_tai_lieuChanging(value);
					this.SendPropertyChanging();
					this._ten_tai_lieu = value;
					this.SendPropertyChanged("ten_tai_lieu");
					this.Onten_tai_lieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tac_gia", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tac_gia
		{
			get
			{
				return this._tac_gia;
			}
			set
			{
				if ((this._tac_gia != value))
				{
					this.Ontac_giaChanging(value);
					this.SendPropertyChanging();
					this._tac_gia = value;
					this.SendPropertyChanged("tac_gia");
					this.Ontac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nha_xuat_ban", DbType="NVarChar(200)")]
		public string nha_xuat_ban
		{
			get
			{
				return this._nha_xuat_ban;
			}
			set
			{
				if ((this._nha_xuat_ban != value))
				{
					this.Onnha_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._nha_xuat_ban = value;
					this.SendPropertyChanged("nha_xuat_ban");
					this.Onnha_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam_xuat_ban", DbType="Int")]
		public System.Nullable<int> nam_xuat_ban
		{
			get
			{
				return this._nam_xuat_ban;
			}
			set
			{
				if ((this._nam_xuat_ban != value))
				{
					this.Onnam_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._nam_xuat_ban = value;
					this.SendPropertyChanged("nam_xuat_ban");
					this.Onnam_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_tai_lieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string loai_tai_lieu
		{
			get
			{
				return this._loai_tai_lieu;
			}
			set
			{
				if ((this._loai_tai_lieu != value))
				{
					this.Onloai_tai_lieuChanging(value);
					this.SendPropertyChanging();
					this._loai_tai_lieu = value;
					this.SendPropertyChanged("loai_tai_lieu");
					this.Onloai_tai_lieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(255)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duong_dan_file", DbType="NVarChar(255)")]
		public string duong_dan_file
		{
			get
			{
				return this._duong_dan_file;
			}
			set
			{
				if ((this._duong_dan_file != value))
				{
					this.Onduong_dan_fileChanging(value);
					this.SendPropertyChanging();
					this._duong_dan_file = value;
					this.SendPropertyChanged("duong_dan_file");
					this.Onduong_dan_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen_truy_cap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string quyen_truy_cap
		{
			get
			{
				return this._quyen_truy_cap;
			}
			set
			{
				if ((this._quyen_truy_cap != value))
				{
					this.Onquyen_truy_capChanging(value);
					this.SendPropertyChanging();
					this._quyen_truy_cap = value;
					this.SendPropertyChanged("quyen_truy_cap");
					this.Onquyen_truy_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_nhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_nhap
		{
			get
			{
				return this._ngay_nhap;
			}
			set
			{
				if ((this._ngay_nhap != value))
				{
					this.Onngay_nhapChanging(value);
					this.SendPropertyChanging();
					this._ngay_nhap = value;
					this.SendPropertyChanged("ngay_nhap");
					this.Onngay_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tai_lieu_ban_sao_tai_lieu", Storage="_ban_sao_tai_lieus", ThisKey="ma_tai_lieu", OtherKey="ma_tai_lieu")]
		public EntitySet<ban_sao_tai_lieu> ban_sao_tai_lieus
		{
			get
			{
				return this._ban_sao_tai_lieus;
			}
			set
			{
				this._ban_sao_tai_lieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phan_loai_tai_lieu_tai_lieu", Storage="_phan_loai_tai_lieu", ThisKey="ma_phan_loai", OtherKey="ma_phan_loai", IsForeignKey=true)]
		public phan_loai_tai_lieu phan_loai_tai_lieu
		{
			get
			{
				return this._phan_loai_tai_lieu.Entity;
			}
			set
			{
				phan_loai_tai_lieu previousValue = this._phan_loai_tai_lieu.Entity;
				if (((previousValue != value) 
							|| (this._phan_loai_tai_lieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phan_loai_tai_lieu.Entity = null;
						previousValue.tai_lieus.Remove(this);
					}
					this._phan_loai_tai_lieu.Entity = value;
					if ((value != null))
					{
						value.tai_lieus.Add(this);
						this._ma_phan_loai = value.ma_phan_loai;
					}
					else
					{
						this._ma_phan_loai = default(int);
					}
					this.SendPropertyChanged("phan_loai_tai_lieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ban_sao_tai_lieus(ban_sao_tai_lieu entity)
		{
			this.SendPropertyChanging();
			entity.tai_lieu = this;
		}
		
		private void detach_ban_sao_tai_lieus(ban_sao_tai_lieu entity)
		{
			this.SendPropertyChanging();
			entity.tai_lieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tai_khoan")]
	public partial class tai_khoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_tai_khoan;
		
		private int _ma_vai_tro;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private string _email;
		
		private string _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _lan_dang_nhap_cuoi;
		
		private EntitySet<ban_doc> _ban_docs;
		
		private EntityRef<vai_tro> _vai_tro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_tai_khoanChanging(int value);
    partial void Onma_tai_khoanChanged();
    partial void Onma_vai_troChanging(int value);
    partial void Onma_vai_troChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onlan_dang_nhap_cuoiChanging(System.Nullable<System.DateTime> value);
    partial void Onlan_dang_nhap_cuoiChanged();
    #endregion
		
		public tai_khoan()
		{
			this._ban_docs = new EntitySet<ban_doc>(new Action<ban_doc>(this.attach_ban_docs), new Action<ban_doc>(this.detach_ban_docs));
			this._vai_tro = default(EntityRef<vai_tro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tai_khoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_tai_khoan
		{
			get
			{
				return this._ma_tai_khoan;
			}
			set
			{
				if ((this._ma_tai_khoan != value))
				{
					this.Onma_tai_khoanChanging(value);
					this.SendPropertyChanging();
					this._ma_tai_khoan = value;
					this.SendPropertyChanged("ma_tai_khoan");
					this.Onma_tai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_vai_tro", DbType="Int NOT NULL")]
		public int ma_vai_tro
		{
			get
			{
				return this._ma_vai_tro;
			}
			set
			{
				if ((this._ma_vai_tro != value))
				{
					if (this._vai_tro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ma_vai_tro = value;
					this.SendPropertyChanged("ma_vai_tro");
					this.Onma_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lan_dang_nhap_cuoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> lan_dang_nhap_cuoi
		{
			get
			{
				return this._lan_dang_nhap_cuoi;
			}
			set
			{
				if ((this._lan_dang_nhap_cuoi != value))
				{
					this.Onlan_dang_nhap_cuoiChanging(value);
					this.SendPropertyChanging();
					this._lan_dang_nhap_cuoi = value;
					this.SendPropertyChanged("lan_dang_nhap_cuoi");
					this.Onlan_dang_nhap_cuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tai_khoan_ban_doc", Storage="_ban_docs", ThisKey="ma_tai_khoan", OtherKey="ma_tai_khoan")]
		public EntitySet<ban_doc> ban_docs
		{
			get
			{
				return this._ban_docs;
			}
			set
			{
				this._ban_docs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vai_tro_tai_khoan", Storage="_vai_tro", ThisKey="ma_vai_tro", OtherKey="ma_vai_tro", IsForeignKey=true)]
		public vai_tro vai_tro
		{
			get
			{
				return this._vai_tro.Entity;
			}
			set
			{
				vai_tro previousValue = this._vai_tro.Entity;
				if (((previousValue != value) 
							|| (this._vai_tro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vai_tro.Entity = null;
						previousValue.tai_khoans.Remove(this);
					}
					this._vai_tro.Entity = value;
					if ((value != null))
					{
						value.tai_khoans.Add(this);
						this._ma_vai_tro = value.ma_vai_tro;
					}
					else
					{
						this._ma_vai_tro = default(int);
					}
					this.SendPropertyChanged("vai_tro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ban_docs(ban_doc entity)
		{
			this.SendPropertyChanging();
			entity.tai_khoan = this;
		}
		
		private void detach_ban_docs(ban_doc entity)
		{
			this.SendPropertyChanging();
			entity.tai_khoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieu_muon_tra")]
	public partial class phieu_muon_tra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_phieu;
		
		private int _ma_ban_doc;
		
		private int _ma_ban_sao;
		
		private System.DateTime _ngay_muon;
		
		private System.DateTime _han_tra;
		
		private System.Nullable<System.DateTime> _ngay_tra;
		
		private string _trang_thai_phieu;
		
		private decimal _tien_phat;
		
		private string _ghi_chu;
		
		private EntityRef<ban_sao_tai_lieu> _ban_sao_tai_lieu;
		
		private EntityRef<ban_doc> _ban_doc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_phieuChanging(int value);
    partial void Onma_phieuChanged();
    partial void Onma_ban_docChanging(int value);
    partial void Onma_ban_docChanged();
    partial void Onma_ban_saoChanging(int value);
    partial void Onma_ban_saoChanged();
    partial void Onngay_muonChanging(System.DateTime value);
    partial void Onngay_muonChanged();
    partial void Onhan_traChanging(System.DateTime value);
    partial void Onhan_traChanged();
    partial void Onngay_traChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_traChanged();
    partial void Ontrang_thai_phieuChanging(string value);
    partial void Ontrang_thai_phieuChanged();
    partial void Ontien_phatChanging(decimal value);
    partial void Ontien_phatChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public phieu_muon_tra()
		{
			this._ban_sao_tai_lieu = default(EntityRef<ban_sao_tai_lieu>);
			this._ban_doc = default(EntityRef<ban_doc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_phieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_phieu
		{
			get
			{
				return this._ma_phieu;
			}
			set
			{
				if ((this._ma_phieu != value))
				{
					this.Onma_phieuChanging(value);
					this.SendPropertyChanging();
					this._ma_phieu = value;
					this.SendPropertyChanged("ma_phieu");
					this.Onma_phieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ban_doc", DbType="Int NOT NULL")]
		public int ma_ban_doc
		{
			get
			{
				return this._ma_ban_doc;
			}
			set
			{
				if ((this._ma_ban_doc != value))
				{
					if (this._ban_doc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_ban_docChanging(value);
					this.SendPropertyChanging();
					this._ma_ban_doc = value;
					this.SendPropertyChanged("ma_ban_doc");
					this.Onma_ban_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ban_sao", DbType="Int NOT NULL")]
		public int ma_ban_sao
		{
			get
			{
				return this._ma_ban_sao;
			}
			set
			{
				if ((this._ma_ban_sao != value))
				{
					if (this._ban_sao_tai_lieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_ban_saoChanging(value);
					this.SendPropertyChanging();
					this._ma_ban_sao = value;
					this.SendPropertyChanged("ma_ban_sao");
					this.Onma_ban_saoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_muon", DbType="Date NOT NULL")]
		public System.DateTime ngay_muon
		{
			get
			{
				return this._ngay_muon;
			}
			set
			{
				if ((this._ngay_muon != value))
				{
					this.Onngay_muonChanging(value);
					this.SendPropertyChanging();
					this._ngay_muon = value;
					this.SendPropertyChanged("ngay_muon");
					this.Onngay_muonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_han_tra", DbType="Date NOT NULL")]
		public System.DateTime han_tra
		{
			get
			{
				return this._han_tra;
			}
			set
			{
				if ((this._han_tra != value))
				{
					this.Onhan_traChanging(value);
					this.SendPropertyChanging();
					this._han_tra = value;
					this.SendPropertyChanged("han_tra");
					this.Onhan_traChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tra", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_tra
		{
			get
			{
				return this._ngay_tra;
			}
			set
			{
				if ((this._ngay_tra != value))
				{
					this.Onngay_traChanging(value);
					this.SendPropertyChanging();
					this._ngay_tra = value;
					this.SendPropertyChanged("ngay_tra");
					this.Onngay_traChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai_phieu", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string trang_thai_phieu
		{
			get
			{
				return this._trang_thai_phieu;
			}
			set
			{
				if ((this._trang_thai_phieu != value))
				{
					this.Ontrang_thai_phieuChanging(value);
					this.SendPropertyChanging();
					this._trang_thai_phieu = value;
					this.SendPropertyChanged("trang_thai_phieu");
					this.Ontrang_thai_phieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tien_phat", DbType="Decimal(10,2) NOT NULL")]
		public decimal tien_phat
		{
			get
			{
				return this._tien_phat;
			}
			set
			{
				if ((this._tien_phat != value))
				{
					this.Ontien_phatChanging(value);
					this.SendPropertyChanging();
					this._tien_phat = value;
					this.SendPropertyChanged("tien_phat");
					this.Ontien_phatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(255)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ban_sao_tai_lieu_phieu_muon_tra", Storage="_ban_sao_tai_lieu", ThisKey="ma_ban_sao", OtherKey="ma_ban_sao", IsForeignKey=true)]
		public ban_sao_tai_lieu ban_sao_tai_lieu
		{
			get
			{
				return this._ban_sao_tai_lieu.Entity;
			}
			set
			{
				ban_sao_tai_lieu previousValue = this._ban_sao_tai_lieu.Entity;
				if (((previousValue != value) 
							|| (this._ban_sao_tai_lieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ban_sao_tai_lieu.Entity = null;
						previousValue.phieu_muon_tras.Remove(this);
					}
					this._ban_sao_tai_lieu.Entity = value;
					if ((value != null))
					{
						value.phieu_muon_tras.Add(this);
						this._ma_ban_sao = value.ma_ban_sao;
					}
					else
					{
						this._ma_ban_sao = default(int);
					}
					this.SendPropertyChanged("ban_sao_tai_lieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ban_doc_phieu_muon_tra", Storage="_ban_doc", ThisKey="ma_ban_doc", OtherKey="ma_ban_doc", IsForeignKey=true)]
		public ban_doc ban_doc
		{
			get
			{
				return this._ban_doc.Entity;
			}
			set
			{
				ban_doc previousValue = this._ban_doc.Entity;
				if (((previousValue != value) 
							|| (this._ban_doc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ban_doc.Entity = null;
						previousValue.phieu_muon_tras.Remove(this);
					}
					this._ban_doc.Entity = value;
					if ((value != null))
					{
						value.phieu_muon_tras.Add(this);
						this._ma_ban_doc = value.ma_ban_doc;
					}
					else
					{
						this._ma_ban_doc = default(int);
					}
					this.SendPropertyChanged("ban_doc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phan_loai_tai_lieu")]
	public partial class phan_loai_tai_lieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_phan_loai;
		
		private string _ten_phan_loai;
		
		private string _ky_hieu;
		
		private string _mo_ta;
		
		private string _tu_khoa;
		
		private EntitySet<tai_lieu> _tai_lieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_phan_loaiChanging(int value);
    partial void Onma_phan_loaiChanged();
    partial void Onten_phan_loaiChanging(string value);
    partial void Onten_phan_loaiChanged();
    partial void Onky_hieuChanging(string value);
    partial void Onky_hieuChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Ontu_khoaChanging(string value);
    partial void Ontu_khoaChanged();
    #endregion
		
		public phan_loai_tai_lieu()
		{
			this._tai_lieus = new EntitySet<tai_lieu>(new Action<tai_lieu>(this.attach_tai_lieus), new Action<tai_lieu>(this.detach_tai_lieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_phan_loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_phan_loai
		{
			get
			{
				return this._ma_phan_loai;
			}
			set
			{
				if ((this._ma_phan_loai != value))
				{
					this.Onma_phan_loaiChanging(value);
					this.SendPropertyChanging();
					this._ma_phan_loai = value;
					this.SendPropertyChanged("ma_phan_loai");
					this.Onma_phan_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_phan_loai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_phan_loai
		{
			get
			{
				return this._ten_phan_loai;
			}
			set
			{
				if ((this._ten_phan_loai != value))
				{
					this.Onten_phan_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_phan_loai = value;
					this.SendPropertyChanged("ten_phan_loai");
					this.Onten_phan_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ky_hieu", DbType="NVarChar(30)")]
		public string ky_hieu
		{
			get
			{
				return this._ky_hieu;
			}
			set
			{
				if ((this._ky_hieu != value))
				{
					this.Onky_hieuChanging(value);
					this.SendPropertyChanging();
					this._ky_hieu = value;
					this.SendPropertyChanged("ky_hieu");
					this.Onky_hieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(255)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tu_khoa", DbType="NVarChar(255)")]
		public string tu_khoa
		{
			get
			{
				return this._tu_khoa;
			}
			set
			{
				if ((this._tu_khoa != value))
				{
					this.Ontu_khoaChanging(value);
					this.SendPropertyChanging();
					this._tu_khoa = value;
					this.SendPropertyChanged("tu_khoa");
					this.Ontu_khoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phan_loai_tai_lieu_tai_lieu", Storage="_tai_lieus", ThisKey="ma_phan_loai", OtherKey="ma_phan_loai")]
		public EntitySet<tai_lieu> tai_lieus
		{
			get
			{
				return this._tai_lieus;
			}
			set
			{
				this._tai_lieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tai_lieus(tai_lieu entity)
		{
			this.SendPropertyChanging();
			entity.phan_loai_tai_lieu = this;
		}
		
		private void detach_tai_lieus(tai_lieu entity)
		{
			this.SendPropertyChanging();
			entity.phan_loai_tai_lieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ban_sao_tai_lieu")]
	public partial class ban_sao_tai_lieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_ban_sao;
		
		private int _ma_tai_lieu;
		
		private string _ma_vach;
		
		private string _vi_tri_kho;
		
		private string _trang_thai;
		
		private System.Nullable<System.DateTime> _ngay_nhap_kho;
		
		private string _ghi_chu;
		
		private EntitySet<phieu_muon_tra> _phieu_muon_tras;
		
		private EntityRef<tai_lieu> _tai_lieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_ban_saoChanging(int value);
    partial void Onma_ban_saoChanged();
    partial void Onma_tai_lieuChanging(int value);
    partial void Onma_tai_lieuChanged();
    partial void Onma_vachChanging(string value);
    partial void Onma_vachChanged();
    partial void Onvi_tri_khoChanging(string value);
    partial void Onvi_tri_khoChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_nhap_khoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_nhap_khoChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public ban_sao_tai_lieu()
		{
			this._phieu_muon_tras = new EntitySet<phieu_muon_tra>(new Action<phieu_muon_tra>(this.attach_phieu_muon_tras), new Action<phieu_muon_tra>(this.detach_phieu_muon_tras));
			this._tai_lieu = default(EntityRef<tai_lieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ban_sao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_ban_sao
		{
			get
			{
				return this._ma_ban_sao;
			}
			set
			{
				if ((this._ma_ban_sao != value))
				{
					this.Onma_ban_saoChanging(value);
					this.SendPropertyChanging();
					this._ma_ban_sao = value;
					this.SendPropertyChanged("ma_ban_sao");
					this.Onma_ban_saoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tai_lieu", DbType="Int NOT NULL")]
		public int ma_tai_lieu
		{
			get
			{
				return this._ma_tai_lieu;
			}
			set
			{
				if ((this._ma_tai_lieu != value))
				{
					if (this._tai_lieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_tai_lieuChanging(value);
					this.SendPropertyChanging();
					this._ma_tai_lieu = value;
					this.SendPropertyChanged("ma_tai_lieu");
					this.Onma_tai_lieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_vach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ma_vach
		{
			get
			{
				return this._ma_vach;
			}
			set
			{
				if ((this._ma_vach != value))
				{
					this.Onma_vachChanging(value);
					this.SendPropertyChanging();
					this._ma_vach = value;
					this.SendPropertyChanged("ma_vach");
					this.Onma_vachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vi_tri_kho", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string vi_tri_kho
		{
			get
			{
				return this._vi_tri_kho;
			}
			set
			{
				if ((this._vi_tri_kho != value))
				{
					this.Onvi_tri_khoChanging(value);
					this.SendPropertyChanging();
					this._vi_tri_kho = value;
					this.SendPropertyChanged("vi_tri_kho");
					this.Onvi_tri_khoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_nhap_kho", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_nhap_kho
		{
			get
			{
				return this._ngay_nhap_kho;
			}
			set
			{
				if ((this._ngay_nhap_kho != value))
				{
					this.Onngay_nhap_khoChanging(value);
					this.SendPropertyChanging();
					this._ngay_nhap_kho = value;
					this.SendPropertyChanged("ngay_nhap_kho");
					this.Onngay_nhap_khoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(255)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ban_sao_tai_lieu_phieu_muon_tra", Storage="_phieu_muon_tras", ThisKey="ma_ban_sao", OtherKey="ma_ban_sao")]
		public EntitySet<phieu_muon_tra> phieu_muon_tras
		{
			get
			{
				return this._phieu_muon_tras;
			}
			set
			{
				this._phieu_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tai_lieu_ban_sao_tai_lieu", Storage="_tai_lieu", ThisKey="ma_tai_lieu", OtherKey="ma_tai_lieu", IsForeignKey=true)]
		public tai_lieu tai_lieu
		{
			get
			{
				return this._tai_lieu.Entity;
			}
			set
			{
				tai_lieu previousValue = this._tai_lieu.Entity;
				if (((previousValue != value) 
							|| (this._tai_lieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tai_lieu.Entity = null;
						previousValue.ban_sao_tai_lieus.Remove(this);
					}
					this._tai_lieu.Entity = value;
					if ((value != null))
					{
						value.ban_sao_tai_lieus.Add(this);
						this._ma_tai_lieu = value.ma_tai_lieu;
					}
					else
					{
						this._ma_tai_lieu = default(int);
					}
					this.SendPropertyChanged("tai_lieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieu_muon_tras(phieu_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.ban_sao_tai_lieu = this;
		}
		
		private void detach_phieu_muon_tras(phieu_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.ban_sao_tai_lieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ban_doc")]
	public partial class ban_doc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_ban_doc;
		
		private int _ma_tai_khoan;
		
		private string _ma_the;
		
		private string _ho_ten;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _gioi_tinh;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private string _loai_ban_doc;
		
		private System.Nullable<System.DateTime> _ngay_cap_the;
		
		private System.Nullable<System.DateTime> _ngay_het_han;
		
		private string _trang_thai_the;
		
		private EntitySet<phieu_muon_tra> _phieu_muon_tras;
		
		private EntityRef<tai_khoan> _tai_khoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_ban_docChanging(int value);
    partial void Onma_ban_docChanged();
    partial void Onma_tai_khoanChanging(int value);
    partial void Onma_tai_khoanChanged();
    partial void Onma_theChanging(string value);
    partial void Onma_theChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onloai_ban_docChanging(string value);
    partial void Onloai_ban_docChanged();
    partial void Onngay_cap_theChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_theChanged();
    partial void Onngay_het_hanChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_het_hanChanged();
    partial void Ontrang_thai_theChanging(string value);
    partial void Ontrang_thai_theChanged();
    #endregion
		
		public ban_doc()
		{
			this._phieu_muon_tras = new EntitySet<phieu_muon_tra>(new Action<phieu_muon_tra>(this.attach_phieu_muon_tras), new Action<phieu_muon_tra>(this.detach_phieu_muon_tras));
			this._tai_khoan = default(EntityRef<tai_khoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ban_doc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_ban_doc
		{
			get
			{
				return this._ma_ban_doc;
			}
			set
			{
				if ((this._ma_ban_doc != value))
				{
					this.Onma_ban_docChanging(value);
					this.SendPropertyChanging();
					this._ma_ban_doc = value;
					this.SendPropertyChanged("ma_ban_doc");
					this.Onma_ban_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tai_khoan", DbType="Int NOT NULL")]
		public int ma_tai_khoan
		{
			get
			{
				return this._ma_tai_khoan;
			}
			set
			{
				if ((this._ma_tai_khoan != value))
				{
					if (this._tai_khoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_tai_khoanChanging(value);
					this.SendPropertyChanging();
					this._ma_tai_khoan = value;
					this.SendPropertyChanged("ma_tai_khoan");
					this.Onma_tai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_the", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ma_the
		{
			get
			{
				return this._ma_the;
			}
			set
			{
				if ((this._ma_the != value))
				{
					this.Onma_theChanging(value);
					this.SendPropertyChanging();
					this._ma_the = value;
					this.SendPropertyChanged("ma_the");
					this.Onma_theChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(15)")]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="NVarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_ban_doc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string loai_ban_doc
		{
			get
			{
				return this._loai_ban_doc;
			}
			set
			{
				if ((this._loai_ban_doc != value))
				{
					this.Onloai_ban_docChanging(value);
					this.SendPropertyChanging();
					this._loai_ban_doc = value;
					this.SendPropertyChanged("loai_ban_doc");
					this.Onloai_ban_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_the", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_cap_the
		{
			get
			{
				return this._ngay_cap_the;
			}
			set
			{
				if ((this._ngay_cap_the != value))
				{
					this.Onngay_cap_theChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_the = value;
					this.SendPropertyChanged("ngay_cap_the");
					this.Onngay_cap_theChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_het_han", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_het_han
		{
			get
			{
				return this._ngay_het_han;
			}
			set
			{
				if ((this._ngay_het_han != value))
				{
					this.Onngay_het_hanChanging(value);
					this.SendPropertyChanging();
					this._ngay_het_han = value;
					this.SendPropertyChanged("ngay_het_han");
					this.Onngay_het_hanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai_the", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string trang_thai_the
		{
			get
			{
				return this._trang_thai_the;
			}
			set
			{
				if ((this._trang_thai_the != value))
				{
					this.Ontrang_thai_theChanging(value);
					this.SendPropertyChanging();
					this._trang_thai_the = value;
					this.SendPropertyChanged("trang_thai_the");
					this.Ontrang_thai_theChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ban_doc_phieu_muon_tra", Storage="_phieu_muon_tras", ThisKey="ma_ban_doc", OtherKey="ma_ban_doc")]
		public EntitySet<phieu_muon_tra> phieu_muon_tras
		{
			get
			{
				return this._phieu_muon_tras;
			}
			set
			{
				this._phieu_muon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tai_khoan_ban_doc", Storage="_tai_khoan", ThisKey="ma_tai_khoan", OtherKey="ma_tai_khoan", IsForeignKey=true)]
		public tai_khoan tai_khoan
		{
			get
			{
				return this._tai_khoan.Entity;
			}
			set
			{
				tai_khoan previousValue = this._tai_khoan.Entity;
				if (((previousValue != value) 
							|| (this._tai_khoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tai_khoan.Entity = null;
						previousValue.ban_docs.Remove(this);
					}
					this._tai_khoan.Entity = value;
					if ((value != null))
					{
						value.ban_docs.Add(this);
						this._ma_tai_khoan = value.ma_tai_khoan;
					}
					else
					{
						this._ma_tai_khoan = default(int);
					}
					this.SendPropertyChanged("tai_khoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieu_muon_tras(phieu_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.ban_doc = this;
		}
		
		private void detach_phieu_muon_tras(phieu_muon_tra entity)
		{
			this.SendPropertyChanging();
			entity.ban_doc = null;
		}
	}
}
#pragma warning restore 1591
